[package]
name = "hex"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
enscoring = {path = "../enscoring"}
thiserror = "1.0"


[dev-dependencies]
hex = "0.4"
