[package]
name = "set1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xor = {path = "../../packages/xor"}
hex = {path = "../../packages/hex"}
aes = {path = "../../packages/aes"}
naivebase64 = {path = "../../packages/naivebase64"}
enscoring = {path = "../../packages/enscoring"}
common = {path = "../../packages/common"}
anyhow = "1.0"